# Generated by Django 6.0.5 on 2026-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archetype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='awakening_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='char_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_agi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_cha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_int',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_str',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stat_wil',
            field=models.FloatField(default=0),
        ),
    ]
