# Generated by Django 6.0.5 on 2026-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_archetype_user_awakening_done_user_char_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='E', max_length=1),
        ),
    ]
