# Generated by Django 6.0.5 on 2026-06-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_aura_user_exp_user_level_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aura',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
