# Generated by Django 6.0.5 on 2026-06-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_aura_remove_user_exp_remove_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stat_agi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat_cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat_wil',
            field=models.IntegerField(default=0),
        ),
    ]
