# Generated by Django 5.2.8 on 2025-12-17 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class', models.CharField(blank=True, max_length=20, null=True)),
                ('is_quiz_completed', models.BooleanField(default=False)),
                ('level', models.PositiveBigIntegerField(default=1)),
                ('xp', models.PositiveBigIntegerField(default=0)),
                ('INT_trophies', models.PositiveBigIntegerField(default=0)),
                ('PER_trophies', models.PositiveBigIntegerField(default=0)),
                ('WIL_trophies', models.PositiveBigIntegerField(default=0)),
                ('CHA_trophies', models.PositiveBigIntegerField(default=0)),
                ('STR_trophies', models.PositiveBigIntegerField(default=0)),
                ('AGI_trophies', models.PositiveBigIntegerField(default=0)),
                ('VIT_trophies', models.PositiveBigIntegerField(default=0)),
                ('END_trophies', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
