# Generated by Django 5.2.8 on 2026-01-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_statquest_userquestprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.statquest')),
            ],
        ),
    ]
