# Generated by Django 5.2.8 on 2026-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stattask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stattask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='stattask',
            name='task',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
