# Generated by Django 6.0.5 on 2026-06-08 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('aura', models.IntegerField()),
                ('rank', models.CharField(default='E', max_length=1)),
                ('str_points', models.FloatField(default=0)),
                ('end_points', models.FloatField(default=0)),
                ('agi_points', models.FloatField(default=0)),
                ('int_points', models.FloatField(default=0)),
                ('cha_points', models.FloatField(default=0)),
                ('wil_points', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
