# Generated by Django 6.0.5 on 2026-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_quest_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_freezes',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
