# Generated by Django 6.0.5 on 2026-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_roadmaptemplate_userroadmap_delete_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_streak_break_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_breaks_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
