# Generated by Django 5.2.6 on 2026-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userprofile_last_streak_break_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_quest_completions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='demotion_immunity_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_roadmap_abandons_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_abandon_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_consecutive_completion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_quest_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
