# Generated by Django 5.1.4 on 2025-07-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentalStats',
            new_name='MentalStat',
        ),
        migrations.RenameModel(
            old_name='PhysicalStats',
            new_name='PhysicalStat',
        ),
    ]
