# Generated by Django 5.1.4 on 2025-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_physicalstat_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalstat',
            name='rank',
            field=models.CharField(default='E', max_length=10),
        ),
    ]
