# Generated by Django 5.1.4 on 2025-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mentalstat_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentalstat',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='physicalstat',
            name='rank',
        ),
    ]
