# Generated by Django 5.1.4 on 2025-07-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rank_remove_mentalstat_rank_remove_physicalstat_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_progress', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
            ],
        ),
    ]
