# Generated by Django 5.2.4 on 2025-08-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentalStat',
        ),
        migrations.DeleteModel(
            name='PhysicalStat',
        ),
    ]
