# Generated by Django 5.2.4 on 2025-08-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_mentalstat_delete_physicalstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rank')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rank')),
            ],
        ),
    ]
