# Generated by Django 5.2.8 on 2025-12-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_questions',
            new_name='Quiz_question',
        ),
    ]
